[pytest]
python_files = *_tests.py test_*.py  # устанавливает правило для имен файлов: по дефолту, кроме второго
python_classes = Test*               # правило для имен классов: по дефолту
python_functions = test_*            # правило для имен функций: по дефолту